spring:
  profiles:
    # 环境标识，本机开发环境有意义,如果觉得污染,可以IDEA 传入--spring.profiles.active=local
    active: local
  lifecycle:
    timeout-per-shutdown-phase: 30s
  application:
    name: internal-gateway
  cloud:
    gateway:
      routes:
        - id: grpc
          uri: http://${user.server.domain.address}
          predicates:
            - Path=/com.seezoon.protocol.user.server.domain.UserAccountService/**
          filters:
            - PreserveHostHeader
    loadbalancer:
      httpclient:
        #https://docs.spring.io/spring-cloud-gateway/docs/3.1.6/reference/html/#http-timeouts-configuration
        connect-timeout: 1000
        response-timeout: 10s
server:
  port: 9200
  http2:
    # 转发grpc
    enabled: true
  ssl:
    enabled: false
