apiVersion: v1
kind: ConfigMap
metadata:
  namespace: user
  name: external-gateway
data:
  application.properties: |-
    listen.port=80
    user.server.app.address=user-server-app.user
---
apiVersion: v1
kind: Service
metadata:
  namespace: user
  name: external-gateway
  labels:
    idc: ${idc}
spec:
  # 默认是，只有集群内部可以访问
  type: ClusterIP
  selector:
    app: external-gateway
  ports:
    - name: external-gateway-service-port
      protocol: TCP
      port: 80
      # 可以写实际pod中端口，也可以引用端口名称
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  namespace: user
  name: external-gateway-${idc}
  labels:
    idc: ${idc}
spec:
  # 默认是，只有集群内部可以访问
  type: ClusterIP
  selector:
    app: external-gateway
    idc: ${idc}
  ports:
    - name: external-gateway-service-port
      protocol: TCP
      port: 80
      # 可以写实际pod中端口，也可以引用端口名称
      targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: user
  name: external-gateway-${idc}
spec:
  selector:
    matchLabels:
      app: external-gateway
      version: v1
      idc: ${idc}
  replicas: 1
  template:
    metadata:
      labels:
        app: external-gateway
        version: v1
        idc: ${idc}
    spec:
      nodeSelector:
        layer: application
        idc: ${idc}
      containers:
        - name: external-gateway
          image: 734839030/external-gateway:1.0.0-SNAPSHOT
          imagePullPolicy: IfNotPresent
          env:
            - name: IDC
              value: ${idc}
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - mountPath: /data/external-gateway/conf/application.properties
              name: external-gateway-config-volume
              subPath: application.properties
      volumes:
        - name: external-gateway-config-volume
          configMap:
            name: external-gateway
            items:
              - key: application.properties
                path: application.properties


