apiVersion: v1
kind: ConfigMap
metadata:
  namespace: user
  name: user-server-domain
data:
  application.properties: |-
    listen.port=80
    user_db.host=docker.for.mac.host.internal
    user_db.port=3306
    user_db.user=root
    user_db.password=12345678
---
apiVersion: v1
kind: Service
metadata:
  namespace: user
  name: user-server-domain
spec:
  # 默认是，只有集群内部可以访问
  type: ClusterIP
  selector:
    app: user-server-domain
  ports:
    - name: user-server-domain-service-port
      protocol: TCP
      port: 80
      # 可以写实际pod中端口，也可以引用端口名称
      targetPort: dubbo
---
apiVersion: v1
kind: Service
metadata:
  namespace: user
  name: user-server-domain-${set}
  labels:
    idc: ${idc}
    set: ${set}
spec:
  # 默认是，只有集群内部可以访问
  type: ClusterIP
  selector:
    app: user-server-domain
    idc: ${idc}
    set: ${set}
  ports:
    - name: user-server-domain-service-port
      protocol: TCP
      port: 80
      # 可以写实际pod中端口，也可以引用端口名称
      targetPort: dubbo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: user
  name: user-server-domain-${set}
spec:
  selector:
    matchLabels:
      app: user-server-domain
      version: v1
      idc: ${idc}
      set: ${set}
  replicas: 2
  template:
    metadata:
      labels:
        app: user-server-domain
        version: v1
        idc: ${idc}
        set: ${set}
    spec:
      nodeSelector:
        layer: application
        idc: ${idc}
      containers:
        - name: user-server-domain
          image: 734839030/user-server-domain:1.0.0-SNAPSHOT
          imagePullPolicy: IfNotPresent
          env:
            - name: IDC
              value: ${idc}
            - name: SET
              value: ${set}
          ports:
            - containerPort: 80
              name: dubbo
          volumeMounts:
            - mountPath: /data/user-server-domain/conf/application.properties
              name: user-server-domain-config-volume
              subPath: application.properties
      volumes:
        - name: user-server-domain-config-volume
          configMap:
            name: user-server-domain
            items:
              - key: application.properties
                path: application.properties


