dubbo:
  application:
    name: ${spring.application.name}
    # wait ms
    shut-wait: 30000
    qos-enable: false
  consumer:
    # ms
    timeout: 5000
    retries: 0
    thread-pool: cached
    core-threads: 0
    threads: 200
  reference:
    com.seezoon.user.server.domain.stub.UserInfoService:
      url: tri://${user.server.domain.address}
    com.seezoon.user.server.domain.stub.UserAccountService:
      url: tri://${internal.gateway.address}
    com.seezoon.middleware.distributed.id.stub.DistributedIdService:
      url: tri://${middleware.distributed.id.address}








