mybatis:
  mapper-locations: classpath*:mappings/**/*.xml
spring:
  datasource:
    url: jdbc:mysql://${user_db.host}:${user_db.port}/distributed_id?useUnicode=true&characterEncoding=utf8&connectTimeout=1000&socketTimeout=60000&rewriteBatchedStatements=true
    username: ${user_db.user}
    password: ${user_db.password}
    hikari:
      minimum-idle: 5
      maximum-pool-size: 100
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 5000
      validation-timeout: 3000
